name: RealGProperty
favicon: null
layout_spectrum: 0.47406
typography_spectrum: 0.10926288878545165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c3c6bf'
    - '#121607'
    - '#4d6b2d'
    - '#00adeb'
  brandStrength: 0.6875
  lightness: 0.7794691100716591
  saturation: 0.006824924377724528
  rhythmicContrast: 0.19129280629567802
purpose: []
